<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>TrabajoFinal_DarioZubaray</RootNamespace>
    <AssemblyName>TrabajoFinal-DarioZubaray</AssemblyName>
    <AssemblyTitle>$(AssemblyName)</AssemblyTitle>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Nullable>disable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <NoWarn>$(NoWarn);CA1416</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\BE\BE.csproj" />
    <ProjectReference Include="..\BLL\BLL.csproj" />
  </ItemGroup>

</Project>
