//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrabajoFinal_DarioZubaray.Properties {
    using System;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TrabajoFinal_DarioZubaray.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }

        internal static string Login_UsernameLabel {
            get {
                return ResourceManager.GetString("Login_UsernameLabel", resourceCulture);
            }
        }

        internal static string Login_PasswordLabel {
            get {
                return ResourceManager.GetString("Login_PasswordLabel", resourceCulture);
            }
        }

        internal static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }

        internal static string Login_MessageInvalid {
            get {
                return ResourceManager.GetString("Login_MessageInvalid", resourceCulture);
            }
        }

        internal static string Login_Developer {
            get {
                return ResourceManager.GetString("Login_Developer", resourceCulture);
            }
        }

        internal static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }

        internal static string Main_MenuFile {
            get {
                return ResourceManager.GetString("Main_MenuFile", resourceCulture);
            }
        }

        internal static string Main_MenuLogout {
            get {
                return ResourceManager.GetString("Main_MenuLogout", resourceCulture);
            }
        }

        internal static string Auth_RequiredFields {
            get {
                return ResourceManager.GetString("Auth_RequiredFields", resourceCulture);
            }
        }

        internal static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }

        internal static string Auth_UserBlocked {
            get {
                return ResourceManager.GetString("Auth_UserBlocked", resourceCulture);
            }
        }

        internal static string Auth_LoginSuccess {
            get {
                return ResourceManager.GetString("Auth_LoginSuccess", resourceCulture);
            }
        }

        internal static string Auth_MaxRetriesExceeded {
            get {
                return ResourceManager.GetString("Auth_MaxRetriesExceeded", resourceCulture);
            }
        }

        internal static string Auth_RetriesLeft {
            get {
                return ResourceManager.GetString("Auth_RetriesLeft", resourceCulture);
            }
        }

        internal static string Role_OptionsCount {
            get {
                return ResourceManager.GetString("Role_OptionsCount", resourceCulture);
            }
        }
    }
}
