//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BE.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BE.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos..
        /// </summary>
        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login exitoso..
        /// </summary>
        public static string Auth_LoginSuccess {
            get {
                return ResourceManager.GetString("Auth_LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario bloqueado por exceso de intentos fallidos. Contacte al administrador..
        /// </summary>
        public static string Auth_MaxRetriesExceeded {
            get {
                return ResourceManager.GetString("Auth_MaxRetriesExceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario y contraseña son obligatorios..
        /// </summary>
        public static string Auth_RequiredFields {
            get {
                return ResourceManager.GetString("Auth_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o contraseña incorrectos. Intentos restantes: {0}.
        /// </summary>
        public static string Auth_RetriesLeft {
            get {
                return ResourceManager.GetString("Auth_RetriesLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario bloqueado. Contacte al administrador..
        /// </summary>
        public static string Auth_UserBlocked {
            get {
                return ResourceManager.GetString("Auth_UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string Login_Button {
            get {
                return ResourceManager.GetString("Login_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a desarrollado por Darío Zubaray.
        /// </summary>
        public static string Login_Developer {
            get {
                return ResourceManager.GetString("Login_Developer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario o Contraseña no válidos!.
        /// </summary>
        public static string Login_MessageInvalid {
            get {
                return ResourceManager.GetString("Login_MessageInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string Login_PasswordLabel {
            get {
                return ResourceManager.GetString("Login_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Iniciar Sesión.
        /// </summary>
        public static string Login_Title {
            get {
                return ResourceManager.GetString("Login_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string Login_UsernameLabel {
            get {
                return ResourceManager.GetString("Login_UsernameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Archivo.
        /// </summary>
        public static string Main_MenuFile {
            get {
                return ResourceManager.GetString("Main_MenuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cerrar Sesión.
        /// </summary>
        public static string Main_MenuLogout {
            get {
                return ResourceManager.GetString("Main_MenuLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Aplicativo Académico.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a {0} opciones.
        /// </summary>
        public static string Role_OptionsCount {
            get {
                return ResourceManager.GetString("Role_OptionsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferencias.
        /// </summary>
        public static string Preferences_Title {
            get {
                return ResourceManager.GetString("Preferences_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma.
        /// </summary>
        public static string Preferences_LanguageLabel {
            get {
                return ResourceManager.GetString("Preferences_LanguageLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string Preferences_SaveButton {
            get {
                return ResourceManager.GetString("Preferences_SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Idioma guardado correctamente.
        /// </summary>
        public static string Preferences_SaveSuccess {
            get {
                return ResourceManager.GetString("Preferences_SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preferencias.
        /// </summary>
        public static string Main_MenuPreferences {
            get {
                return ResourceManager.GetString("Main_MenuPreferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string Main_MenuChangePassword {
            get {
                return ResourceManager.GetString("Main_MenuChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administración.
        /// </summary>
        public static string Main_MenuAdministration {
            get {
                return ResourceManager.GetString("Main_MenuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuarios.
        /// </summary>
        public static string Main_MenuUsers {
            get {
                return ResourceManager.GetString("Main_MenuUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Usuarios.
        /// </summary>
        public static string UserManagement_Title {
            get {
                return ResourceManager.GetString("UserManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo.
        /// </summary>
        public static string UserManagement_New {
            get {
                return ResourceManager.GetString("UserManagement_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar.
        /// </summary>
        public static string UserManagement_Edit {
            get {
                return ResourceManager.GetString("UserManagement_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string UserManagement_Delete {
            get {
                return ResourceManager.GetString("UserManagement_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Buscar.
        /// </summary>
        public static string UserManagement_Search {
            get {
                return ResourceManager.GetString("UserManagement_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea eliminar el usuario "{0}"?.
        /// </summary>
        public static string UserManagement_DeleteConfirm {
            get {
                return ResourceManager.GetString("UserManagement_DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario eliminado correctamente..
        /// </summary>
        public static string UserManagement_DeleteSuccess {
            get {
                return ResourceManager.GetString("UserManagement_DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un usuario de la grilla..
        /// </summary>
        public static string UserManagement_SelectUser {
            get {
                return ResourceManager.GetString("UserManagement_SelectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario:.
        /// </summary>
        public static string UserManagement_SearchLabel {
            get {
                return ResourceManager.GetString("UserManagement_SearchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nuevo Usuario.
        /// </summary>
        public static string UserForm_NewTitle {
            get {
                return ResourceManager.GetString("UserForm_NewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Editar Usuario.
        /// </summary>
        public static string UserForm_EditTitle {
            get {
                return ResourceManager.GetString("UserForm_EditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre de usuario.
        /// </summary>
        public static string UserForm_UserNameLabel {
            get {
                return ResourceManager.GetString("UserForm_UserNameLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string UserForm_PasswordLabel {
            get {
                return ResourceManager.GetString("UserForm_PasswordLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Activo.
        /// </summary>
        public static string UserForm_IsActiveLabel {
            get {
                return ResourceManager.GetString("UserForm_IsActiveLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol.
        /// </summary>
        public static string UserForm_RoleLabel {
            get {
                return ResourceManager.GetString("UserForm_RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Guardar.
        /// </summary>
        public static string UserForm_Save {
            get {
                return ResourceManager.GetString("UserForm_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string UserForm_Cancel {
            get {
                return ResourceManager.GetString("UserForm_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre de usuario es obligatorio..
        /// </summary>
        public static string UserForm_UserNameRequired {
            get {
                return ResourceManager.GetString("UserForm_UserNameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña es obligatoria..
        /// </summary>
        public static string UserForm_PasswordRequired {
            get {
                return ResourceManager.GetString("UserForm_PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario guardado correctamente..
        /// </summary>
        public static string UserForm_UserSaved {
            get {
                return ResourceManager.GetString("UserForm_UserSaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Administrador.
        /// </summary>
        public static string UserForm_RoleAdmin {
            get {
                return ResourceManager.GetString("UserForm_RoleAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string UserForm_RoleUser {
            get {
                return ResourceManager.GetString("UserForm_RoleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar Contraseña.
        /// </summary>
        public static string ChangePassword_Title {
            get {
                return ResourceManager.GetString("ChangePassword_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña actual.
        /// </summary>
        public static string ChangePassword_CurrentLabel {
            get {
                return ResourceManager.GetString("ChangePassword_CurrentLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nueva contraseña.
        /// </summary>
        public static string ChangePassword_NewLabel {
            get {
                return ResourceManager.GetString("ChangePassword_NewLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string ChangePassword_ConfirmLabel {
            get {
                return ResourceManager.GetString("ChangePassword_ConfirmLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cambiar.
        /// </summary>
        public static string ChangePassword_ChangeButton {
            get {
                return ResourceManager.GetString("ChangePassword_ChangeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancelar.
        /// </summary>
        public static string ChangePassword_CancelButton {
            get {
                return ResourceManager.GetString("ChangePassword_CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Todos los campos son obligatorios.
        /// </summary>
        public static string ChangePassword_RequiredFields {
            get {
                return ResourceManager.GetString("ChangePassword_RequiredFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Las contraseñas no coinciden.
        /// </summary>
        public static string ChangePassword_PasswordsMismatch {
            get {
                return ResourceManager.GetString("ChangePassword_PasswordsMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La contraseña actual es incorrecta.
        /// </summary>
        public static string ChangePassword_InvalidCurrent {
            get {
                return ResourceManager.GetString("ChangePassword_InvalidCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña cambiada correctamente.
        /// </summary>
        public static string ChangePassword_Success {
            get {
                return ResourceManager.GetString("ChangePassword_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ☺.
        /// </summary>
        public static string ChangePassword_GroupBox {
            get {
                return ResourceManager.GetString("ChangePassword_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ☺.
        /// </summary>
        public static string Preferences_GroupBox {
            get {
                return ResourceManager.GetString("Preferences_GroupBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario:.
        /// </summary>
        public static string Main_FooterUser {
            get {
                return ResourceManager.GetString("Main FooterUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol:.
        /// </summary>
        public static string Main_FooterRole {
            get {
                return ResourceManager.GetString("Main FooterRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Roles.
        /// </summary>
        public static string Main_MenuRoles {
            get {
                return ResourceManager.GetString("Main_MenuRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Gestión de Roles.
        /// </summary>
        public static string RoleManagement_Title {
            get {
                return ResourceManager.GetString("RoleManagement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Rol:.
        /// </summary>
        public static string RoleManagement_RoleLabel {
            get {
                return ResourceManager.GetString("RoleManagement_RoleLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Crear Rol.
        /// </summary>
        public static string RoleManagement_Create {
            get {
                return ResourceManager.GetString("RoleManagement_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Eliminar.
        /// </summary>
        public static string RoleManagement_Delete {
            get {
                return ResourceManager.GetString("RoleManagement_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Disponibles.
        /// </summary>
        public static string RoleManagement_Available {
            get {
                return ResourceManager.GetString("RoleManagement_Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Asignados.
        /// </summary>
        public static string RoleManagement_Assigned {
            get {
                return ResourceManager.GetString("RoleManagement_Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &gt;&gt;.
        /// </summary>
        public static string RoleManagement_Add {
            get {
                return ResourceManager.GetString("RoleManagement_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a &lt;&lt;.
        /// </summary>
        public static string RoleManagement_Remove {
            get {
                return ResourceManager.GetString("RoleManagement_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El nombre del rol es obligatorio..
        /// </summary>
        public static string RoleManagement_NameRequired {
            get {
                return ResourceManager.GetString("RoleManagement_NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Seleccione un rol de la lista..
        /// </summary>
        public static string RoleManagement_SelectRole {
            get {
                return ResourceManager.GetString("RoleManagement_SelectRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a ¿Está seguro que desea eliminar el rol "{0}"?.
        /// </summary>
        public static string RoleManagement_ConfirmDelete {
            get {
                return ResourceManager.GetString("RoleManagement_ConfirmDelete", resourceCulture);
            }
        }
    }
}
